import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

const compatDoc = readFileSync(new URL('../docs/x402-v211-paid-mcp-compatibility.md', import.meta.url), 'utf8');
const registryDoc = readFileSync(new URL('../docs/mcp-registry-listing-proof.md', import.meta.url), 'utf8');
const registryJson = JSON.parse(readFileSync(new URL('../docs/mcp-registry-listing.json', import.meta.url), 'utf8'));
const llms = readFileSync(new URL('../llms.txt', import.meta.url), 'utf8');
const readme = readFileSync(new URL('../README.md', import.meta.url), 'utf8');
const packageJson = JSON.parse(readFileSync(new URL('../package.json', import.meta.url), 'utf8'));
const x402Source = readFileSync(new URL('../src/tools/x402.ts', import.meta.url), 'utf8');
const sessionSource = readFileSync(new URL('../src/tools/session.ts', import.meta.url), 'utf8');

describe('x402 v2.11 compatibility docs', () => {
  it('covers paid MCP header, CORS, Streamable HTTP, receipt, and cutover requirements', () => {
    for (const required of [
      'Payment-Signature',
      'X-Payment',
      'payment-response',
      'mcp-session-id',
      'Access-Control-Expose-Headers: payment-response, mcp-session-id',
      'tools/list',
      'tools/call',
      'https://sepolia.basescan.org/tx/<txHash>',
      'https://basescan.org/tx/<txHash>',
      'Base Sepolia to Base mainnet cutover checklist',
    ]) {
      expect(compatDoc).toContain(required);
    }
  });
});

describe('directory-grade metadata proof', () => {
  it('packages registry/listing docs and llms.txt', () => {
    expect(packageJson.files).toContain('llms.txt');
    expect(packageJson.files).toContain('docs/*.json');
    expect(readme).toContain('docs/mcp-registry-listing-proof.md');
    expect(readme).toContain('llms.txt');
  });

  it('declares registry, listing, and Glama proof surfaces', () => {
    for (const required of [
      'docs/mcp-registry-listing.json',
      'glama.json',
      'smithery.yaml',
      'https://glama.ai/mcp/servers/up2itnow0822/claw-pay-mcp',
      'do not claim directory hosting',
    ]) {
      expect(registryDoc).toContain(required);
    }
    expect(registryJson.package).toBe('agentpay-mcp');
    expect(registryJson.mcp_name).toBe('io.github.up2itnow0822/agentpay');
    expect(registryJson.listing_proofs.glama).toContain('glama.ai');
  });

  it('gives LLM crawlers use and do-not-use guidance', () => {
    expect(llms).toContain('Use AgentPay MCP when');
    expect(llms).toContain('Do not use AgentPay MCP as a managed-wallet custody service');
    expect(llms).toContain('docs/x402-v211-paid-mcp-compatibility.md');
  });

  it('updates paid tool descriptions with use and do-not-use guidance plus field detail', () => {
    expect(x402Source).toContain('Use when an agent needs one capped x402 paid HTTP request');
    expect(x402Source).toContain('Do not use when the endpoint is an uninitialized Streamable HTTP MCP session');
    expect(x402Source).toContain('Payment-Signature is generated by the x402 client after policy approval');
    expect(sessionSource).toContain('Use when a paid endpoint supports a reusable x402 session');
    expect(sessionSource).toContain('Do not use before initialize/session creation');
    expect(sessionSource).toContain('Maximum ETH-equivalent payment cap');
  });
});
